config/routes.rb
Rails.application.routes.draw do
  get 'mypages/index'
  get 'top/index'
  devise_for :users
  root 'top#index'
  resources :users, only: [:show, :edit, :update]
  resources :mypages, only: [:index, :new, :show, :create]
  resources :post_pdf, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mypage.rb
class Mypage < ApplicationRecord
  belongs_to :user
  has_many :post_pdf
end

app/models/post_pdf.rb
class PostPdf < ApplicationRecord
  belongs_to :user
  has_many :mypage
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :mypages
  has_many :post_pdfs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    mypages_path(resource)
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
                                        :user_name,
                                        :depart,
                                        :position,
                                        :phone
                                      ])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def index
    @mypages = Mypage.all
  end

  def new
    @mypage = Mypage.new
  end

  def show
  end

  def create
    Mypage.create(mypage_params)
  end

  private

  def mypage_params
    params.require(:mypage).permit(
      :est_number,
      :issue_date,
      :exp_date,
      :destination,
      :title,
      :dl_date,
      :terms,
      :initial1,
      :initial1_vol,
      :initial1_price,
      :initial1_memo,
      :initial2,
      :initial2_vol,
      :initial2_price,
      :initial2_memo,
      :initial3,
      :initial3_vol,
      :initial3_price,
      :initial3_memo,
      :run1,
      :run1_vol,
      :run1_price,
      :run1_memo,
      :run2,
      :run2_vol,
      :run2_price,
      :run2_memo,
      :run3,
      :run3_vol,
      :run3_price,
      :run3_memo,
      :run4,
      :run4_vol,
      :run4_price,
      :run4_memo,
      :run5,
      :run5_vol,
      :run5_price,
      :run5_memo,
      :run6,
      :run6_vol,
      :run6_price,
      :run6_memo,
      :run7,
      :run7_vol,
      :run7_price,
      :run7_memo,
      :run8,
      :run8_vol,
      :run8_price,
      :run8_memo,
      :run9,
      :run9_vol,
      :run9_price,
      :run9_memo
    ).merge(user_id: current_user.id)
  end
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  def index
  end

  def sample_doc
    report = Thinreports::Report.new(layout: "#{Rails.root}/app/pdfs/test.tlf")

    report.start_new_page
    # さっき作った title に value つっこんでる
    report.page.item(:title).value('PDFやで')
    # title 以外はあとでやるのでここではスルーします

    file = report.generate
    send_data(
      file,
      filename: 'filename_sample.pdf',
      type: 'application/pdf',
      disposition: 'inline'
    )
  end
end

app/controllers/post_pdf_controller.rb
class PostPdfController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.pdf do
        post_pdf = PracticePdf::PostPdf.new
        send_data post_pdf.render,
                  filename: '20220120_知多工業様_概算御見積.pdf',
                  type: 'application/pdf',
                  disposition: 'inline' # 外すとダウンロード
      end
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user.user_name
    @mypages = current_user.mypages
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to mypages_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>EST-Portal</title>

    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="app/assets/stylesheets/mypage.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="app/javascript/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
  </body>
</html>

app/views/mypages/_est_show_all.html.erb
<h2>最新見積一覧</h2>

<table class="table">
<thead>
<tr>
<th scope="col">見積管理番号</th>
<th scope="col">発行日</th>
<th scope="col">宛先</th>
<th scope="col">件名</th>
<th scope="col">提供条件</th>
<th scope="col">詳細</th>
<th scope="col">PDF出力</th>
<th>
</tr>
</thead>

<tbody>
<% @mypages.each do |m| %>
<tr>
<th scope="row"><%= m.est_number %></th>
<td><%= m.issue_date %></td>
<td><%= m.destination %></td>
<td><%= m.title %></td>
<td><%= m.terms %></td>
<td><button type="button" class="btn btn-outline-primary">
<%= link_to "詳細", '#' %></td>
<td><button type="button" class="btn btn-outline-primary">
<%= link_to "表示", post_pdf_index_path(format: "pdf"), target: :_blank, rel: "noopener noreferrer" %></button></td>
</tr>
<% end %>
<tbody>
</table>
</div>

app/views/mypages/_footer.html.erb
</main>
<footer class="py-4 bg-light mt-auto">
  <div class="container-fluid px-4">
    <div class="d-flex align-items-center justify-content-between small">
      <div class="text-muted">Copyright &copy; EST-Portal 2022</div>
    </div>
  </div>
</footer>

app/views/mypages/_main-top.html.erb
<main>
<div class="container-fluid px-4">
    <h1><span class="mt-4 badge bg-success">MyPage</span></h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">
            <%= current_user.depart %>
            <%= current_user.position %>
            <%= current_user.user_name %></li>
    </ol>
    <div class="row">
        <div class="col-xl-3 col-md-6">
            <div class="card bg-primary text-white mb-4">
                <div class="card-body">新規作成</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <%= link_to "見積書の新規作成", new_mypage_path, class: "small text-white stretched-link" %>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-secondary text-white mb-4">
                <div class="card-body">見積一覧</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <%= link_to '作成した見積一覧', user_path(current_user), class: "small text-white stretched-link" %>  
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-success text-white mb-4">
                <div class="card-body">設定</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <%= link_to '登録情報の編集', edit_user_path(current_user), class: "small text-white stretched-link" %>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-danger text-white mb-4">
                <div class="card-body">ログアウト</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <%= link_to "", destroy_user_session_path, method: :delete, class: "small text-white stretched-link" %>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
    </div>

app/views/mypages/_navbar.html.erb
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <%= link_to "EST-Portal", mypages_index_path, class: "navbar-brand ps-3" %>


            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#!">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>

app/views/mypages/_sidenav-footer.html.erb
<div class="sb-sidenav-footer">
  <div class="small">Logged in as:</div>
    <!-- 現在ログイン中ユーザーの氏名表示 -->
    <%= current_user.user_name %>
</div>
</nav>
</div>
<div id="layoutSidenav_content">

app/views/mypages/_sidenav-menu.html.erb
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <div class="sb-sidenav-menu-heading">menu</div>
            <li><%= link_to "トップページ", mypages_index_path, class: "nav-link" %></li>
                    <li><%= link_to "新規作成", new_mypage_path, class: "nav-link" %></li>
                    <li><%= link_to "見積一覧", user_path(current_user), class: "nav-link" %></li>
                    <li><%= link_to '設定', edit_user_path(current_user), class: "nav-link" %></li>
                    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
                </div>
            </div>

app/views/mypages/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/mypages/index.html.erb
<body class="sb-nav-fixed">
<%= render 'navbar'%>
<%= render 'sidenav-menu'%>
<%= render 'sidenav-footer'%>
<%= render 'main-top'%>

<!-- メインコンテンツ -->
<%= render 'est_show_all' %>

<script src="app/javascript/mypege_scripts.js"></script>
</body>
<%= render 'footer'%>

app/views/mypages/new.html.erb
<body class="sb-nav-fixed">
    <%= render 'navbar'%>
    <%= render 'sidenav-menu'%>
    <%= render 'sidenav-footer'%>
    <%= render 'main-top'%>

<!-- メインコンテンツ -->
<h2>新規見積作成</h2>

<%= form_with model: @mypage, local: true do |f| %>
<!-- 基本情報 -->
<table class="table">
<thead>
<tr>
<th scope="col">見積管理番号</th>
<th scope="col">発行日</th>
<th scope="col">有効期限</th>
<th scope="col">納期</th>
<th scope="col">提供条件</th>
<th>
</tr>
</thead>

<tbody>
<tr>
<td><%= f.text_field :est_number %></td>
<td><%= f.text_field :issue_date %></td>
<td><%= f.text_field :exp_date %></td>
<td><%= f.text_field :dl_date %></td>
<td><%= f.text_field :terms %></td>
</tr>
<tbody>
</table>

<!-- 宛先・件名 -->
<table class="table">
<thead>
<tr>
<th scope="col">宛　先<br><%= f.text_field :destination, size: 55 %></th>
<th scope="col">件　名<br><%= f.text_field :title, size: 55 %></th>
</tr>
</thead>
</table>
<br>

<!-- 初期費用 -->
<h3>初期費用</h3>
<table class="table">
<thead>
<tr>
<th scope="col">項　目</th>
<th scope="col">数　量</th>
<th scope="col">単　価</th>
<th scope="col">合　計</th>
<th scope="col">備　考</th>
</tr>
</thead>

<tbody>
<tr>
<td><%= f.text_field :initial1, size:35 %></td>
<td><%= f.text_field :initial1_vol, size:10 %></td>
<td><%= f.text_field :initial1_price, size:10 %></td>
<td></td>
<td><%= f.text_field :initial1_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :initial2, size:35 %></td>
<td><%= f.text_field :initial2_vol, size:10 %></td>
<td><%= f.text_field :initial2_price, size:10 %></td>
<td></td>
<td><%= f.text_field :initial2_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :initial3, size:35 %></td>
<td><%= f.text_field :initial3_vol, size:10 %></td>
<td><%= f.text_field :initial3_price, size:10 %></td>
<td></td>
<td><%= f.text_field :initial3_memo, size:35 %></td>
</tr>
</tbody>
</table>
<br>

<!-- 月額費用 -->
<h3>月額費用</h3>
<table class="table">
<thead>
<tr>
<th scope="col">項　目</th>
<th scope="col">数　量</th>
<th scope="col">単　価</th>
<th scope="col">合　計</th>
<th scope="col">備　考</th>
</tr>
</thead>

<tbody>
<tr>
<td><%= f.text_field :run1, size:35 %></td>
<td><%= f.text_field :run1_vol, size:10 %></td>
<td><%= f.text_field :run1_price, size:10 %></td>
<td></td>
<td><%= f.text_field :run1_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :run2, size:35 %></td>
<td><%= f.text_field :run2_vol, size:10 %></td>
<td><%= f.text_field :run2_price, size:10 %></td>
<td></td>
<td><%= f.text_field :run2_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :run3, size:35 %></td>
<td><%= f.text_field :run3_vol, size:10 %></td>
<td><%= f.text_field :run3_price, size:10 %></td>
<td></td>
<td><%= f.text_field :run3_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :run4, size:35 %></td>
<td><%= f.text_field :run4_vol, size:10 %></td>
<td><%= f.text_field :run4_price, size:10 %></td>
<td></td>
<td><%= f.text_field :run4_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :run5, size:35 %></td>
<td><%= f.text_field :run5_vol, size:10 %></td>
<td><%= f.text_field :run5_price, size:10 %></td>
<td></td>
<td><%= f.text_field :run5_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :run6, size:35 %></td>
<td><%= f.text_field :run6_vol, size:10 %></td>
<td><%= f.text_field :run6_price, size:10 %></td>
<td><%= f.text_field :run6_price, size:10 %></td>
<td><%= f.text_field :run6_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :run7, size:35 %></td>
<td><%= f.text_field :run7_vol, size:10 %></td>
<td><%= f.text_field :run7_price, size:10 %></td>
<td><%= f.text_field :run7_price, size:10 %></td>
<td><%= f.text_field :run7_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :run8, size:35 %></td>
<td><%= f.text_field :run8_vol, size:10 %></td>
<td><%= f.text_field :run8_price, size:10 %></td>
<td><%= f.text_field :run8_price, size:10 %></td>
<td><%= f.text_field :run8_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :run9, size:35 %></td>
<td><%= f.text_field :run9_vol, size:10 %></td>
<td><%= f.text_field :run9_price, size:10 %></td>
<td><%= f.text_field :run9_price, size:10 %></td>
<td><%= f.text_field :run9_memo, size:35 %></td>
</tr>

<tr>
<td><%= f.text_field :run3, size:35 %></td>
<td><%= f.text_field :run3_vol, size:10 %></td>
<td><%= f.text_field :run3_price, size:10 %></td>
<td><%= f.text_field :run3_price, size:10 %></td>
<td><%= f.text_field :run3_memo, size:35 %></td>
</tr>
</tbody>
</table>

<button type="button" class="btn btn-outline-primary">
<%= f.submit "作成", class: 'btn'%></button>
<% end %>



        <%# <h3>月額費用</h3>

        <div class='form-floating mb-3'>
            <div class='px-5'><%= f.label :項目１%>
            <%# <div class='px-5'><%= f.text_field :run1 %>
        <%# </div>

        <div class='form-floating mb-3'>
            <div class='px-5'><%= f.label :数量%>
            <%# <div class='px-5'><%= f.text_field :run1_vol %>
        <%# </div> %>

        <%# <div class='form-floating mb-3'> %>
            <%# <div class='px-5'><%= f.label :単価%>
            <%# <div class='px-5'><%= f.text_field :run1_price %>
        <%# </div>

        <div class='form-floating mb-3'>
            <div class='px-5'><%= f.label :備考%>
            <%# <div class='px-5'><%= f.text_field :run1_memo %>
        <%# </div> %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="app/javascript/mypege_scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="app/assets/mypage/chart-area-demo.js"></script>
    <script src="app/assets/mypage/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="app/javascript/datatables-simple-demo.js"></script>
</body>

<%= render 'footer'%>

app/views/mypages/show.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>マイページ</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="app/assets/stylesheets/mypage.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    </head>

    <body class="sb-nav-fixed">
        <%= render 'navbar'%>
        <%= render 'sidenav-menu'%>
        <%= render 'sidenav-footer'%>
        <%= render 'main-top'%>

<!-- メインコンテンツ -->
            <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                            見積一覧
                            </div>

                            <%= link_to "PDFを表示", record_pdfs_index(format: "pdf") %>
                            <div class="card-body">
                                <table id="datatablesSimple">
                                </table>
                            </div>
                        </div>
                    </div>
                </main>
            <%= render 'footer'%>
            </div>
        </div>

<div class="wrapper">
    <h1 id="header"></h1>
    <div id="next-prev-button">
        <button id="prev" onclick="prev()">‹</button>
        <button id="next" onclick="next()">›</button>
    </div>
    <div id="calendar"></div>
</div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="app/javascript/mypege_scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="app/assets/mypage/chart-area-demo.js"></script>
        <script src="app/assets/mypage/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="app/javascript/datatables-simple-demo.js"></script>
    </body>

                    </div>
                </main>
            <%= render 'footer'%>
            </div>
        </div>
</html>

app/views/pdfs/index.html.erb
<h1>PDFにしてくれる君</h1>
<p>
  <%= link_to 'サンプル書類がみたい', pdfs_sample_doc_path %>
</p>

app/views/pdfs/sample_doc.html.erb
<h1>Pdfs#sample_doc</h1>
<p>Find me in app/views/pdfs/sample_doc.html.erb</p>

app/views/top/_login_form.html.erb
<% unless user_signed_in? %>
  <section class="page-section" id="login">
    <div class="container px-4 px-lg-5">
      <h2 class="text-center text-warning mt-0">LOGIN</h2>

      <hr class="divider"/>

      <%= form_with model: @user, url: user_session_path, local: true do |f| %>
        <%= f.email_field :email, id:"email", placeholder:"email" %><br>
        <%= f.password_field :password, id:"password", placeholder:"password" %>
        <div>
          <br><%= f.submit "LOGIN" %>
        </div>
      <% end %>
    </div>
  </section>
<% end %>

app/views/top/_masthead.html.erb
<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">
          EST-Portal
        </h1>
  
        <hr class="divider my-4"/>

        <!-- Login -->
        <%= render 'login_form' %>
      </div>

      <div class="col-lg-8 align-self-baseline">
      </div>
    </div>
  </div>
</header>

app/views/top/_navigation.html.erb
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
      <div class="container px-4 px-lg-5">
        <%= link_to('EST-Portal', root_path, {class: "navbar-brand"})%>
        
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto my-2 my-lg-0">
          <% unless user_signed_in? %>
            <li class="nav-item"><a class="nav-link" href="#new_account">新規登録</a></li>
              <li class="nav-item">
                <%= link_to('ログイン', root_path, {class: "nav-link"}) %>
                
                <% else %>
                  <li class="nav-item">
                    <%= link_to('マイページ', mypages_index_path, {class: "nav-link"}) %></li>
                  
                  <li class="nav-item">
                    <%= link_to'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/top/index.html.erb
<body id="page-top">
  <!-- Navigation-->
  <%= render 'navigation' %>

  <!-- Masthead-->
  <%= render 'masthead' %>

  <!-- NewAccount-->
  <% unless user_signed_in? %>
  <%= render 'new_account' %>
  <% end %>

  <!-- Footer-->
  <footer class="bg-light py-5">
    <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2022 - EST-Portal</div></div>
  </footer>
</body>

app/views/users/show.html.erb
<body class="sb-nav-fixed">
  <%= render 'mypages/navbar'%>
  <%= render 'mypages/sidenav-menu'%>
  <%= render 'mypages/sidenav-footer'%>
  <%= render 'mypages/main-top'%>

<!-- メインコンテンツ -->
<h2>作成見積一覧</h2>

<table class="table">
<thead>
<tr>
<th scope="col">見積管理番号</th>
<th scope="col">発行日</th>
<th scope="col">宛先</th>
<th scope="col">件名</th>
<th scope="col">提供条件</th>
<th scope="col">詳細・編集</th>
<th scope="col">PDF出力</th>
<th>
</tr>
</thead>

<tbody>
<% @mypages.each do |m| %>
<tr>
<th scope="row"><%= m.est_number %></th>
<td><%= m.issue_date %></td>
<td><%= m.destination %></td>
<td><%= m.title %></td>
<td><%= m.terms %></td>
<td><button type="button" class="btn btn-outline-primary">
<%= link_to "表示", '#' %></td>
<td><button type="button" class="btn btn-outline-primary">
<%= link_to "表示", post_pdf_index_path(format: "pdf"), target: :_blank, rel: "noopener noreferrer" %></button></td>
</tr>
<% end %>
<tbody>
</table>


</body>

<%= render 'mypages/footer'%>